# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SKROLLIE' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # Pods for SKROLLIE
  
  pod 'SkyFloatingLabelTextField', '~> 3.0' # Text Filed.
  pod 'IQKeyboardManagerSwift' # KeyBord.
  pod 'SwiftMessages' # Pop up.
  pod 'Alamofire' # Json Function.
  pod 'SwiftyJSON' # Model MVC.
  pod 'SVPinView', '~> 1.0' #For OTP.
  pod 'SRCountdownTimer' # For Timer.
  pod 'SwiftyComments'
  pod 'AWSS3'
  pod 'KMPlaceholderTextView'
  pod 'ScalingCarousel'
  pod 'EasyTipView'
  pod 'SDWebImage'
  
  # https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
  end
  
end
